version: '3.8'

services:
    postgres:
        image: postgres:15
        container_name: postgres_db
        environment:
            POSTGRES_USER: your_username
            POSTGRES_PASSWORD: your_password
            POSTGRES_DB: your_database
        ports:
            - "5432:5432"
        volumes:
            - postgres_data:/var/lib/postgresql/data
        networks:
            - backend

    redis:
        image: redis:alpine
        container_name: redis_cache
        ports:
            - "6379:6379"
        networks:
            - backend
        volumes:
            - redis_data:/data

volumes:
    postgres_data:
    redis_data:

networks:
    backend:
        driver: bridge
